server:
  port: 8085

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/smartdesk
    username: smartdesk_user
    password: smartdesk_pass
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/