server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        # User Service routes (no auth needed for login/register)
        - id: user-service-public
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        # User Service routes (auth required)
        - id: user-service-private
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
            - AuthFilter

        # Ticket Service routes (auth required)
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**,/api/comments/**
          filters:
            - StripPrefix=0
            - AuthFilter

        # AI Service routes (auth required)
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=0
            - AuthFilter

        # Notification Service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0
            - AuthFilter

        # Analytics Service
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=0
            - AuthFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: smartdesk-super-secret-key-must-be-32-chars-minimum

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway